name: UtilityUI
version: 1.0
main: navy.otter.UtilityUI.UtilityUI
api-version: 1.13
commands:
  uui:
    description: main function
    aliases: [utilityui, ui]
    permission: UtilityUI.admin
    permission-message: "Du hast keine ausreichende Berechtigung für diesen Befehl."
permissions:
  UtilityUI.admin:
    description: "Full access to all tools."
    default: op
    children:
      UtilityUI.chests: true
      UtilityUI.brewing: true
      UtilityUI.commandblock: true
      UtilityUI.debugstick: true
      UtilityUI.workbench: true
  UtilityUI.chests:
    default: false
  UtilityUI.brewing:
    description: "Access a personal brewing stand GUI."
    default: false
  UtilityUI.commandblock:
    default: false
  UtilityUI.debugstick:
    default: false
  UtilityUI.workbench:
    default: false
